// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allocated_storage_gb" {
  type = number
}
variable "backup_retention_days" {
  type    = number
  default = 7
}
variable "database_name" {
  type = string
}
variable "db_version" {
  type = string
}
variable "high_availability" {
  type    = bool
  default = false
}
variable "instance_size" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "multi_az_zones" {
  type    = number
  default = 2
}
variable "network" {
  type = object({
    cidr   = string
    id     = string
    region = optional(string)
    subnets = list(object({
      availability_zone = optional(string)
      cidr              = string
      id                = string
      type              = optional(string)
    }))
  })
}
variable "subnet_filter" {
  type    = string
  default = null
}
variable "username" {
  type = string
}
