// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = optional(string)
  })
}
variable "billing_mode" {
  type = string
}
variable "enable_streams" {
  type    = bool
  default = false
}
variable "hash_key" {
  type = string
}
variable "hash_key_type" {
  type    = string
  default = "S"
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "range_key" {
  type    = string
  default = null
}
variable "range_key_type" {
  type    = string
  default = "S"
}
variable "read_capacity" {
  type    = number
  default = 5
}
variable "region" {
  type = string
}
variable "stream_view_type" {
  type    = string
  default = "NEW_AND_OLD_IMAGES"
}
variable "table_name" {
  type = string
}
variable "write_capacity" {
  type    = number
  default = 5
}
