// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "bucket" {
  type = object({
    endpoint = optional(string)
    id       = string
    name     = string
    policies = list(object({
      id   = string
      name = string
    }))
    region = optional(string)
  })
  default = null
}
variable "bucket_policy" {
  type    = string
  default = null
}
variable "cpu_limit" {
  type    = string
  default = "500m"
}
variable "database" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    high_availability = optional(bool)
    id                = string
    policies = list(object({
      id   = string
      name = string
    }))
    version = optional(string)
  })
}
variable "database_policy" {
  type    = string
  default = null
}
variable "domain_name" {
  type = string
}
variable "environment" {
  type = string
}
variable "health_check_path" {
  type    = string
  default = "/health"
}
variable "image" {
  type = string
}
variable "log_level" {
  type    = string
  default = "info"
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "memory_limit" {
  type    = string
  default = "512Mi"
}
variable "network" {
  type = object({
    cidr   = string
    id     = string
    region = optional(string)
    subnets = list(object({
      availability_zone = optional(string)
      cidr              = string
      id                = string
      type              = optional(string)
    }))
  })
}
variable "port" {
  type = number
}
variable "replicas" {
  type = number
}
