// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "dynamodb_policy" {
  type    = string
  default = null
}
variable "dynamodb_table" {
  type = object({
    arn  = string
    name = string
    policies = list(object({
      id   = string
      name = string
    }))
    region     = string
    stream_arn = string
  })
}
variable "lambda_memory_mb" {
  type = number
}
variable "lambda_timeout_sec" {
  type = number
}
variable "log_retention_days" {
  type    = number
  default = 7
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "region" {
  type = string
}
