// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = optional(string)
  })
}
variable "cluster_name" {
  type = string
}
variable "fargate_namespaces" {
  type = list(string)
}
variable "kubernetes_version" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "vpc" {
  type = object({
    account_id = optional(string)
    arn        = optional(string)
    cidr       = string
    id         = string
    region     = string
    security_group_ids = optional(object({
      default   = optional(string)
      endpoints = optional(string)
    }))
    subnets = list(object({
      availability_zone = string
      cidr              = string
      id                = string
      type              = string
    }))
  })
}
