// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "azure_service_principal" {
  type = object({
    client_id       = string
    client_secret   = string
    subscription_id = string
    tenant_id       = string
  })
}
variable "azure_virtual_wan" {
  type = object({
    id                         = string
    resource_group_name        = string
    location                   = string
    virtual_hub_id             = string
    virtual_hub_address_prefix = string
    vpn_gateway_id             = optional(string)
  })
  default = null
}
variable "cidr" {
  type = string
}
variable "dns_servers" {
  type    = list(string)
  default = []
}
variable "enable_ddos_protection" {
  type    = bool
  default = false
}
variable "location" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "subnets" {
  type = list(object({
    cidr              = string
    name              = string
    service_endpoints = optional(list(string))
  }))
}
