// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn = string
    external_id = string
  })
}
variable "az_count" {
  type = number
  default = 2
}
variable "cidr" {
  type = string
  default = "10.0.0.0/16"
}
variable "enable_flow_logs" {
  type = bool
  default = true
}
variable "flow_log_retention_days" {
  type = number
  default = 30
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "region" {
  type = string
  default = "us-east-1"
}
