// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allow_delete_with_contents" {
  type    = bool
  default = false
}
variable "analyst_access" {
  type = string
}
variable "analysts" {
  type    = list(string)
  default = []
}
variable "analytics_login" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    schema = string
    shared_tables = list(object({
      access = string
      schema = string
      table  = string
    }))
  })
}
variable "dataset_name" {
  type = string
}
variable "encryption_key" {
  type    = string
  default = ""
}
variable "gcp_service_account" {
  type = object({
    auth_provider_x509_cert_url = string
    auth_uri                    = string
    client_email                = string
    client_id                   = string
    client_x509_cert_url        = string
    private_key                 = string
    private_key_id              = string
    project_id                  = string
    token_uri                   = string
    type                        = string
    universe_domain             = string
  })
}
variable "keep_saved_tables_for_days" {
  type    = number
  default = 0
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "postgres_cluster" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    high_availability   = optional(bool)
    id                  = string
    management_hostname = optional(string)
    policies = list(object({
      id   = string
      name = string
    }))
    version = optional(string)
  })
}
