// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allowed_domains" {
  type = list(string)
}
variable "api" {
  type = object({
    api_id        = string
    custom_domain = optional(string)
    execution_arn = optional(string)
    region        = string
    stage         = optional(string)
    url           = string
  })
}
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "google_client_id" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
