// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allocated_storage_gb" {
  type = number
}
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = optional(string)
  })
}
variable "backup_retention_days" {
  type = number
}
variable "database_name" {
  type = string
}
variable "deletion_protection" {
  type = bool
}
variable "engine_version" {
  type = string
}
variable "iam_database_auth" {
  type    = bool
  default = true
}
variable "instance_class" {
  type = string
}
variable "master_password" {
  type    = string
  default = null
}
variable "max_allocated_storage_gb" {
  type = number
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "multi_az" {
  type = bool
}
variable "performance_insights_enabled" {
  type    = bool
  default = false
}
variable "read_replica_count" {
  type = number
}
variable "storage_encrypted" {
  type    = bool
  default = true
}
variable "username" {
  type = string
}
variable "vpc" {
  type = object({
    account_id = optional(string)
    arn        = optional(string)
    cidr       = string
    id         = string
    region     = string
    security_group_ids = optional(object({
      default   = optional(string)
      endpoints = optional(string)
    }))
    subnets = list(object({
      availability_zone = string
      cidr              = string
      id                = string
      type              = string
    }))
  })
}
