// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allocated_storage_gb" {
  type    = number
  default = 20
}
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "backup_retention_days" {
  type    = number
  default = 7
}
variable "database_name" {
  type    = string
  default = "app"
}
variable "db_version" {
  type    = string
  default = "16"
}
variable "high_availability" {
  type    = bool
  default = false
}
variable "instance_size" {
  type    = string
  default = "s"
}
variable "max_storage_gb" {
  type    = number
  default = 100
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "network" {
  type = object({
    cidr                      = string
    default_security_group_id = optional(string)
    region                    = string
    subnets = list(object({
      availability_zone = string
      cidr              = string
      id                = string
      name              = string
      tier              = string
    }))
    vpc_id = string
  })
}
variable "placement_subnet" {
  type    = string
  default = null
}
variable "storage_autoscaling" {
  type    = bool
  default = false
}
variable "username" {
  type    = string
  default = "app_user"
}
