// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allocated_storage_gb" {
  type = number
  default = 20
}
variable "aws_authentication" {
  type = object({
    arn = string
    external_id = string
  })
}
variable "backup_retention_days" {
  type = number
  default = 7
}
variable "database_name" {
  type = string
  default = "appdb"
}
variable "db_version" {
  type = string
  default = "16"
}
variable "deletion_protection" {
  type = bool
  default = true
}
variable "instance_size" {
  type = string
  default = "xs"
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "multi_az" {
  type = bool
  default = false
}
variable "network" {
  type = object({
    cidr = string
    ecr_vpc_endpoint_ids = optional(list(string))
    nat_gateway_id = optional(string)
    region = string
    s3_vpc_endpoint_id = optional(string)
    subnets = list(object({
      availability_zone = string
      cidr = string
      id = string
      type = string
    }))
    vpc_id = string
  })
}
variable "skip_final_snapshot" {
  type = bool
  default = false
}
variable "username" {
  type = string
  default = "appuser"
}
