// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "code_key" {
  type    = string
  default = "app.zip"
}
variable "code_source" {
  type    = string
  default = "bundle"
}
variable "enable_dead_letter_queue" {
  type    = bool
  default = false
}
variable "gateway" {
  type = object({
    endpoint      = string
    execution_arn = string
    id            = string
    region        = optional(string)
    stage         = optional(string)
  })
  default = null
}
variable "handler" {
  type = string
}
variable "log_level" {
  type    = string
  default = "info"
}
variable "log_retention_days" {
  type    = number
  default = 365
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "memory_mb" {
  type    = number
  default = 512
}
variable "network" {
  type = object({
    cidr   = string
    id     = string
    region = optional(string)
    subnets = list(object({
      availability_zone = optional(string)
      cidr              = string
      id                = string
      type              = optional(string)
    }))
  })
  default = null
}
variable "region" {
  type = string
}
variable "reserved_concurrency" {
  type    = number
  default = -1
}
variable "route_key" {
  type    = string
  default = "$default"
}
variable "runtime" {
  type = string
}
variable "starting_hit_points" {
  type    = number
  default = 20
}
variable "table" {
  type = object({
    arn           = string
    name          = string
    partition_key = optional(string)
    policies = list(object({
      id   = string
      name = string
    }))
    region   = optional(string)
    sort_key = optional(string)
  })
}
variable "table_access" {
  type    = string
  default = null
}
variable "timeout_seconds" {
  type    = number
  default = 30
}
variable "tracing_enabled" {
  type    = bool
  default = false
}
variable "world_height" {
  type    = number
  default = 600
}
variable "world_width" {
  type    = number
  default = 1000
}
