// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "acm_certificate_arn" {
  type = string
}
variable "aws_authentication" {
  type = object({
    arn = string
    external_id = string
  })
}
variable "domain_name" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "price_class" {
  type = string
  default = "PriceClass_100"
}
variable "redirects" {
  type = list(object({
    from = string
    status_code = number
    to = string
  }))
  default = []
}
variable "region" {
  type = string
  default = "us-east-1"
}
