// Generated by Terraform from the `redirects` param. Runs as a CloudFront
// Function (viewer-request) in front of every request to the site.
var redirects = ${redirects};

function handler(event) {
  var request = event.request;
  var uri = request.uri;

  if (redirects.hasOwnProperty(uri)) {
    var r = redirects[uri];
    return {
      statusCode: r.status,
      statusDescription: statusText(r.status),
      headers: { location: { value: r.to } },
    };
  }

  // Trailing-slash / directory-index handling, without redirecting the
  // browser: "/", "/about/", and "/about" (no extension) all resolve to
  // their own index.html.
  if (uri.endsWith("/")) {
    request.uri = uri + "index.html";
  } else if (!uri.includes(".")) {
    request.uri = uri + "/index.html";
  }

  return request;
}

function statusText(code) {
  if (code === 301) return "Moved Permanently";
  if (code === 302) return "Found";
  if (code === 308) return "Permanent Redirect";
  return "Found";
}
