// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "api" {
  type = object({
    api_id        = string
    custom_domain = optional(string)
    execution_arn = optional(string)
    region        = string
    stage         = optional(string)
    url           = string
  })
}
variable "attach_to_network" {
  type    = bool
  default = false
}
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "code_source" {
  type = string
}
variable "environment" {
  type    = map(string)
  default = {}
}
variable "image_tag" {
  type    = string
  default = "latest"
}
variable "landing_zone" {
  type = object({
    network = object({
      cidr              = optional(string)
      region            = string
      security_group_id = optional(string)
      subnet_ids        = list(string)
      vpc_id            = string
    })
    registry = object({
      arn         = optional(string)
      name        = string
      region      = string
      registry_id = optional(string)
      url         = string
    })
    repository = object({
      clone_url      = optional(string)
      default_branch = string
      full_name      = string
      url            = string
    })
    team = string
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "memory_mb" {
  type    = number
  default = 512
}
variable "name" {
  type = string
}
variable "route" {
  type = string
}
variable "timeout_seconds" {
  type    = number
  default = 10
}
