// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "borrowed" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    read       = list(string)
    read_write = list(string)
  })
  default = null
}
variable "container_registry" {
  type = object({
    format   = optional(string)
    id       = string
    location = optional(string)
    name     = string
    policies = list(object({
      id   = string
      name = string
    }))
    registry_url = string
  })
}
variable "database" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    schema = string
    shared_tables = list(object({
      access = string
      schema = string
      table  = string
    }))
  })
  default = null
}
variable "environment_variables" {
  type = list(object({
    name  = string
    value = string
  }))
  default = []
}
variable "gcp_service_account" {
  type = object({
    auth_provider_x509_cert_url = string
    auth_uri                    = string
    client_email                = string
    client_id                   = string
    client_x509_cert_url        = string
    private_key                 = string
    private_key_id              = string
    project_id                  = string
    token_uri                   = string
    type                        = string
    universe_domain             = string
  })
}
variable "max_instances" {
  type = number
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "min_instances" {
  type = number
}
variable "public_access" {
  type    = bool
  default = false
}
variable "region" {
  type = string
}
variable "service_name" {
  type = string
}
variable "size" {
  type = string
}
variable "vpc_connector" {
  type = object({
    id      = string
    name    = string
    network = optional(string)
    region  = string
  })
  default = null
}
