// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "apply_immediately" {
  type    = bool
  default = true
}
variable "at_rest_encryption_enabled" {
  type = bool
}
variable "auth_token_enabled" {
  type = bool
}
variable "automatic_failover_enabled" {
  type = bool
}
variable "aws_vpc" {
  type = object({
    cidr = string
    id   = string
    subnets = list(object({
      cidr = string
      id   = string
      type = optional(string)
    }))
  })
}
variable "engine_version" {
  type = string
}
variable "maintenance" {
  type = object({
    auto_minor_version_upgrade   = optional(bool)
    preferred_maintenance_window = optional(string)
    snapshot_window              = optional(string)
  })
  default = null
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "multi_az_enabled" {
  type = bool
}
variable "node_type" {
  type = string
}
variable "num_cache_clusters" {
  type = number
}
variable "port" {
  type = number
}
variable "region" {
  type = string
}
variable "snapshot_retention_limit" {
  type = number
}
variable "transit_encryption_enabled" {
  type = bool
}
variable "use_case" {
  type = string
}
