// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "kubernetes_version" {
  type    = string
  default = "1.31"
}
variable "max_nodes" {
  type    = number
  default = 3
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "min_nodes" {
  type    = number
  default = 1
}
variable "network" {
  type = object({
    cidr                      = string
    default_security_group_id = optional(string)
    region                    = string
    subnets = list(object({
      availability_zone = string
      cidr              = string
      id                = string
      name              = string
      tier              = string
    }))
    vpc_id = string
  })
}
variable "node_instance_size" {
  type    = string
  default = "s"
}
variable "public_api_endpoint" {
  type    = bool
  default = true
}
