// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn = string
    external_id = string
  })
}
variable "engine_version" {
  type = string
  default = "8.0"
}
variable "high_availability" {
  type = bool
  default = false
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "network" {
  type = object({
    cidr = string
    ecr_vpc_endpoint_ids = optional(list(string))
    nat_gateway_id = optional(string)
    region = string
    s3_vpc_endpoint_id = optional(string)
    subnets = list(object({
      availability_zone = string
      cidr = string
      id = string
      type = string
    }))
    vpc_id = string
  })
}
variable "node_size" {
  type = string
  default = "xs"
}
