// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn = string
    external_id = string
  })
}
variable "cache" {
  type = object({
    auth = object({
      hostname = string
      password = optional(string)
      port = number
    })
    engine = string
    id = string
    region = optional(string)
    tls_enabled = bool
    version = optional(string)
  })
}
variable "cluster" {
  type = object({
    ca_certificate = string
    cluster_name = string
    endpoint = string
    ingress_certificate_arn = optional(string)
    ingress_class_name = string
    node_security_group_id = optional(string)
    oidc_provider_arn = string
    oidc_provider_url = string
    region = string
  })
}
variable "container_port" {
  type = number
  default = 8080
}
variable "cpu_limit" {
  type = string
  default = "250m"
}
variable "cronjobs" {
  type = list(object({
    command = list(string)
    name = string
    schedule = string
  }))
  default = []
}
variable "database" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port = number
      username = string
    })
    engine = string
    high_availability = optional(bool)
    id = string
    region = string
    version = optional(string)
  })
}
variable "email" {
  type = object({
    configuration_set = optional(string)
    domain = string
    region = string
    smtp = object({
      host = string
      password = string
      port = number
      username = string
    })
  })
}
variable "health_check_path" {
  type = string
  default = "/healthz"
}
variable "image" {
  type = string
  default = "public.ecr.aws/docker/library/nginx:stable"
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "memory_limit" {
  type = string
  default = "256Mi"
}
variable "queue" {
  type = object({
    arn = string
    dlq_arn = optional(string)
    dlq_url = optional(string)
    id = string
    name = string
    policies = list(object({
      id = string
      name = string
    }))
    region = string
    url = string
  })
}
variable "queue_policy" {
  type = string
  default = null
}
variable "replicas" {
  type = number
  default = 2
}
variable "storage" {
  type = object({
    endpoint = optional(string)
    id = string
    kms_key_arn = optional(string)
    name = string
    policies = list(object({
      id = string
      name = string
    }))
    region = string
  })
}
variable "storage_policy" {
  type = string
  default = null
}
