// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "admin_email" {
  type = string
}
variable "admin_username" {
  type    = string
  default = "admin_user"
}
variable "blog_title" {
  type    = string
  default = "Our Blog"
}
variable "database" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    high_availability = optional(bool)
    id                = string
    policies = list(object({
      id   = string
      name = string
    }))
    version = optional(string)
  })
}
variable "database_policy" {
  type = string
}
variable "kubernetes_cluster" {
  type = object({
    authentication = object({
      cluster = map(string)
      user = object({
        token = string
      })
    })
    id              = string
    name            = optional(string)
    oidc_issuer_url = optional(string)
    version         = optional(string)
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "replicas" {
  type    = number
  default = 1
}
variable "service_type" {
  type    = string
  default = "LoadBalancer"
}
