// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "capacity" {
  type    = string
  default = "on_demand"
}
variable "deletion_protection" {
  type    = bool
  default = false
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "partition_key" {
  type = string
}
variable "point_in_time_recovery" {
  type    = bool
  default = true
}
variable "read_capacity" {
  type    = number
  default = 5
}
variable "region" {
  type = string
}
variable "sort_key" {
  type    = string
  default = null
}
variable "table_name" {
  type = string
}
variable "ttl_attribute" {
  type    = string
  default = null
}
variable "write_capacity" {
  type    = number
  default = 5
}
