// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allocation_id" {
  type    = string
  default = ""
}
variable "cidr" {
  type = string
}
variable "ipam_endpoint" {
  type    = string
  default = ""
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "pool" {
  type = string
}
variable "region" {
  type = string
}
variable "register_with_ipam" {
  type    = bool
  default = false
}
