// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "allocated_storage" {
  type = number
}
variable "aws_vpc" {
  type = object({
    cidr = string
    id   = string
    subnets = list(object({
      cidr = string
      id   = string
      type = optional(string)
    }))
  })
}
variable "backup_retention_period" {
  type = number
}
variable "database_name" {
  type = string
}
variable "deletion_protection" {
  type = bool
}
variable "engine_version" {
  type = string
}
variable "instance_class" {
  type = string
}
variable "maintenance" {
  type = object({
    auto_minor_version_upgrade   = optional(bool)
    preferred_backup_window      = optional(string)
    preferred_maintenance_window = optional(string)
  })
  default = null
}
variable "max_allocated_storage" {
  type    = number
  default = 100
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "monitoring" {
  type = object({
    enhanced_monitoring_interval = optional(number)
  })
  default = null
}
variable "multi_az" {
  type = bool
}
variable "performance_insights_enabled" {
  type    = bool
  default = false
}
variable "region" {
  type = string
}
variable "skip_final_snapshot" {
  type    = bool
  default = false
}
variable "username" {
  type = string
}
