// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "azure_service_principal" {
  type = object({
    client_id       = string
    client_secret   = string
    subscription_id = string
    tenant_id       = string
  })
}
variable "backup_retention_days" {
  type    = number
  default = 7
}
variable "database_name" {
  type = string
}
variable "db_version" {
  type = string
}
variable "geo_redundant_backup" {
  type    = bool
  default = false
}
variable "high_availability" {
  type    = bool
  default = false
}
variable "instance_size" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "network" {
  type = object({
    account_id     = optional(string)
    cidr           = string
    dns_servers    = optional(list(string))
    id             = string
    name           = string
    region         = string
    resource_group = optional(string)
    subnets = list(object({
      cidr       = string
      delegation = optional(string)
      id         = string
      name       = string
    }))
  })
}
variable "storage_gb" {
  type = number
}
variable "username" {
  type = string
}
