// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "access_level" {
  type = string
}
variable "bucket_name" {
  type = string
}
variable "cors_allowed_origins" {
  type    = list(string)
  default = []
}
variable "lifecycle_rules" {
  type = list(object({
    storage_class         = string
    transition_after_days = number
  }))
  default = []
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "object_lock" {
  type    = bool
  default = false
}
variable "object_lock_retention_days" {
  type    = number
  default = 2557
}
variable "versioning_enabled" {
  type    = bool
  default = true
}
