// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "login_name" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "postgres_cluster" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    high_availability   = optional(bool)
    id                  = string
    management_hostname = optional(string)
    policies = list(object({
      id   = string
      name = string
    }))
    version = optional(string)
  })
}
variable "read" {
  type    = list(string)
  default = []
}
variable "read_write" {
  type    = list(string)
  default = []
}
