// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "cidr" {
  type = string
}
variable "dns_servers" {
  type    = list(string)
  default = []
}
variable "enable_flow_logs" {
  type    = bool
  default = false
}
variable "flow_log_retention_days" {
  type    = number
  default = 30
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "subnets" {
  type = list(object({
    cidr = string
    name = string
    type = optional(string)
  }))
}
