// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "network" {
  type = object({
    availability_zones    = list(string)
    available_cidr_blocks = optional(list(string))
    cidr                  = string
    nat_gateway_ids       = optional(list(string))
    public_subnet_ids     = optional(list(string))
    region                = string
    vpc_id                = string
  })
}
variable "network_slice" {
  type = string
}
variable "registry" {
  type = object({
    arn         = optional(string)
    name        = string
    region      = string
    registry_id = optional(string)
    url         = string
  })
}
variable "repository" {
  type = object({
    clone_url      = optional(string)
    default_branch = string
    full_name      = string
    url            = string
  })
}
variable "team" {
  type = string
}
