// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "azure_service_principal" {
  type = object({
    client_id       = string
    client_secret   = string
    subscription_id = string
    tenant_id       = string
  })
}
variable "bucket" {
  type = object({
    account_id = optional(string)
    container  = string
    endpoint   = string
    id         = string
    name       = string
    policies = list(object({
      id   = string
      name = string
    }))
    region = optional(string)
  })
  default = null
}
variable "bucket_policy" {
  type    = string
  default = null
}
variable "cpu" {
  type = string
}
variable "database" {
  type = object({
    auth = object({
      database = string
      hostname = string
      password = string
      port     = number
      username = string
    })
    high_availability = optional(bool)
    id                = string
    policies = list(object({
      id   = string
      name = string
    }))
    version = optional(string)
  })
  default = null
}
variable "database_policy" {
  type    = string
  default = null
}
variable "health_check_path" {
  type    = string
  default = "/"
}
variable "image" {
  type = string
}
variable "log_level" {
  type    = string
  default = "info"
}
variable "max_replicas" {
  type = number
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "memory" {
  type = string
}
variable "min_replicas" {
  type = number
}
variable "network" {
  type = object({
    account_id     = optional(string)
    cidr           = string
    dns_servers    = optional(list(string))
    id             = string
    name           = string
    region         = string
    resource_group = optional(string)
    subnets = list(object({
      cidr       = string
      delegation = optional(string)
      id         = string
      name       = string
    }))
  })
}
variable "port" {
  type = number
}
variable "public_ingress" {
  type    = bool
  default = true
}
