// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "description" {
  type    = string
  default = ""
}
variable "github" {
  type = object({
    app_id              = optional(string)
    app_installation_id = optional(string)
    app_private_key     = optional(string)
    owner               = string
    token               = optional(string)
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "registry" {
  type = object({
    arn         = optional(string)
    name        = string
    region      = string
    registry_id = optional(string)
    url         = string
  })
}
variable "repository_name" {
  type = string
}
variable "seed_starter_files" {
  type    = bool
  default = true
}
variable "visibility" {
  type = string
}
