// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "azure_service_principal" {
  type = object({
    client_id       = string
    client_secret   = string
    subscription_id = string
    tenant_id       = string
  })
}
variable "azure_virtual_network" {
  type = object({
    cidr                = string
    id                  = string
    location            = string
    resource_group_name = string
    subnets = list(object({
      cidr = string
      id   = string
      name = string
    }))
  })
}
variable "backup" {
  type = object({
    enable         = optional(bool)
    retention_days = optional(number)
  })
  default = null
}
variable "location" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "private_endpoints" {
  type = object({
    enable_function_app = optional(bool)
    enable_storage      = optional(bool)
    subnet_name         = optional(string)
  })
  default = null
}
variable "runtime" {
  type = object({
    name    = string
    version = string
  })
}
variable "sku" {
  type = object({
    size = string
    tier = string
  })
}
variable "storage" {
  type = object({
    enable_https_only = optional(bool)
    replication_type  = optional(string)
  })
  default = null
}
