// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "cidr" {
  type = string
}
variable "connector_cidr" {
  type = string
}
variable "connector_machine_type" {
  type    = string
  default = "e2-micro"
}
variable "connector_max_instances" {
  type    = number
  default = 3
}
variable "connector_min_instances" {
  type    = number
  default = 2
}
variable "connector_region" {
  type = string
}
variable "enable_flow_logs" {
  type    = bool
  default = true
}
variable "gcp_service_account" {
  type = object({
    auth_provider_x509_cert_url = string
    auth_uri                    = string
    client_email                = string
    client_id                   = string
    client_x509_cert_url        = string
    private_key                 = string
    private_key_id              = string
    project_id                  = string
    token_uri                   = string
    type                        = string
    universe_domain             = string
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "private_service_access_enabled" {
  type    = bool
  default = true
}
variable "private_service_access_prefix_length" {
  type    = number
  default = 20
}
variable "subnets" {
  type = list(object({
    cidr   = string
    name   = string
    region = string
    secondary_ranges = optional(list(object({
      cidr = string
      name = string
    })))
  }))
}
